[package]
name = "goveectl"
version = "0.1.0"
edition = "2024"
license = "MIT"
categories = ["command-line-utilities", "api-bindings", "network-programming"]
description = "A small CLI for managing LAN-enabled Govee light products through their publicly-available API."
repository = "https://github.com/uhhJoyz/goveectl"
readme = "README.md"
include = [
  "**/*.rs"
]

[dependencies]
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_with = "3.21.0"
tokio = { version = "1.53.1", features = ["full"] }
toml = "1.1.4"
